use serde::Serialize;use std::{collections::HashMap,path::Path,time::{SystemTime,UNIX_EPOCH}};use walkdir::WalkDir;
#[derive(Serialize,Clone)]#[serde(rename_all="camelCase")]struct FolderStat{path:String,name:String,file_count:u64,total_bytes:u64,extensions:HashMap<String,u64>,recent_modified:Option<u64>,representative_files:Vec<String>,keywords:Vec<String>}
#[derive(Serialize)]#[serde(rename_all="camelCase")]struct ScanResult{root:String,scanned_at:u64,folder_count:u64,file_count:u64,total_bytes:u64,excluded_count:u64,folders:Vec<FolderStat>}
fn excluded(name:&str)->bool{matches!(name.to_ascii_lowercase().as_str(),"node_modules"|".git"|".svn"|".hg"|"target"|"dist"|"build"|".next"|".vite"|"cache"|".cache"|"temp"|"tmp"|"__pycache__")}
fn tokens(name:&str)->Vec<String>{let stem=Path::new(name).file_stem().and_then(|s|s.to_str()).unwrap_or(name);stem.split(|c:char|!c.is_alphanumeric()&&c!='가'&&c!='힣').filter(|s|s.chars().count()>=2).map(|s|s.to_lowercase()).collect()}
#[tauri::command]fn scan_folder(root:String)->Result<ScanResult,String>{let rp=Path::new(&root);if !rp.is_dir(){return Err("선택한 경로가 폴더가 아닙니다.".into())}let mut map:HashMap<String,FolderStat>=HashMap::new();let mut excluded_count=0u64;
let walker=WalkDir::new(rp).follow_links(false).into_iter().filter_entry(|e|{if e.depth()==0{return true}let ex=e.file_type().is_dir()&&excluded(&e.file_name().to_string_lossy());if ex{excluded_count+=1} !ex});
for ent in walker.filter_map(Result::ok){if ent.file_type().is_dir(){continue}let md=match ent.metadata(){Ok(v)=>v,Err(_)=>continue};let parent=ent.path().parent().unwrap_or(rp);let key=parent.to_string_lossy().to_string();let name=parent.file_name().and_then(|s|s.to_str()).unwrap_or("").to_string();let st=map.entry(key.clone()).or_insert(FolderStat{path:key,name,file_count:0,total_bytes:0,extensions:HashMap::new(),recent_modified:None,representative_files:vec![],keywords:vec![]});st.file_count+=1;st.total_bytes+=md.len();if let Some(ext)=ent.path().extension().and_then(|s|s.to_str()){*st.extensions.entry(ext.to_ascii_lowercase()).or_insert(0)+=1}if st.representative_files.len()<8{st.representative_files.push(ent.file_name().to_string_lossy().to_string())}if let Ok(m)=md.modified().and_then(|x|x.duration_since(UNIX_EPOCH).map_err(std::io::Error::other)){let t=m.as_secs();st.recent_modified=Some(st.recent_modified.unwrap_or(0).max(t))}let mut freq:HashMap<String,u32>=HashMap::new();for f in &st.representative_files{for t in tokens(f){*freq.entry(t).or_insert(0)+=1}}let mut kv:Vec<_>=freq.into_iter().collect();kv.sort_by(|a,b|b.1.cmp(&a.1));st.keywords=kv.into_iter().take(6).map(|x|x.0).collect();}
let mut folders:Vec<_>=map.into_values().collect();folders.sort_by(|a,b|b.file_count.cmp(&a.file_count));let file_count=folders.iter().map(|f|f.file_count).sum();let total_bytes=folders.iter().map(|f|f.total_bytes).sum();let folder_count=folders.len() as u64;let scanned_at=SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_secs()*1000;Ok(ScanResult{root,scanned_at,folder_count,file_count,total_bytes,excluded_count,folders})}
#[cfg_attr(mobile,tauri::mobile_entry_point)]pub fn run(){tauri::Builder::default().plugin(tauri_plugin_dialog::init()).invoke_handler(tauri::generate_handler![scan_folder]).run(tauri::generate_context!()).expect("error while running FileOrbit");}