use serde::{Deserialize,Serialize};use std::{collections::{HashMap,HashSet},fs::OpenOptions,io::{BufRead,BufReader,Write},path::{Component,Path},time::{SystemTime,UNIX_EPOCH}};use tauri::Manager;use walkdir::WalkDir;
#[derive(Serialize,Clone)]#[serde(rename_all="camelCase")]struct FolderStat{path:String,name:String,file_count:u64,total_bytes:u64,extensions:HashMap<String,u64>,recent_modified:Option<u64>,representative_files:Vec<String>,keywords:Vec<String>}
#[derive(Serialize)]#[serde(rename_all="camelCase")]struct DownloadFile{name:String,path:String,size:u64,modified:Option<u64>}
#[derive(Deserialize,Clone)]#[serde(rename_all="camelCase")]struct MovePlanItem{source:String,target:String}
#[derive(Serialize)]#[serde(rename_all="camelCase")]struct HistoryDetail{transaction_id:String,entries:Vec<JournalEntry>}
#[derive(Serialize)]#[serde(rename_all="camelCase")]struct HistoryItem{transaction_id:String,timestamp:u64,moved:u64,undone:u64,failed:u64,can_undo:bool}
#[derive(Serialize)]#[serde(rename_all="camelCase")]struct MoveExecution{transaction_id:String,moved:u64,failed:u64,results:Vec<MoveValidation>}
#[derive(Serialize,Deserialize,Clone)]#[serde(rename_all="camelCase")]struct JournalEntry{transaction_id:String,timestamp:u64,source:String,target:String,status:String,error:Option<String>}
#[derive(Serialize)]#[serde(rename_all="camelCase")]struct MoveValidation{source:String,target:String,ok:bool,reason:String}
#[derive(Serialize)]#[serde(rename_all="camelCase")]struct ScanResult{root:String,scanned_at:u64,folder_count:u64,file_count:u64,total_bytes:u64,excluded_count:u64,folders:Vec<FolderStat>}
fn excluded(name:&str)->bool{matches!(name.to_ascii_lowercase().as_str(),"node_modules"|".git"|".svn"|".hg"|"target"|"dist"|"build"|".next"|".vite"|"cache"|".cache"|"temp"|"tmp"|"__pycache__"|"windows"|"program files"|"program files (x86)"|"$recycle.bin"|"system volume information")}
fn tokens(name:&str)->Vec<String>{let stem=Path::new(name).file_stem().and_then(|s|s.to_str()).unwrap_or(name);stem.split(|c:char|!c.is_alphanumeric()&&c!='가'&&c!='힣').filter(|s|s.chars().count()>=2).map(|s|s.to_lowercase()).collect()}
fn finalize(st:&mut FolderStat){let mut freq:HashMap<String,u32>=HashMap::new();for f in &st.representative_files{for t in tokens(f){*freq.entry(t).or_insert(0)+=1}}let mut kv:Vec<_>=freq.into_iter().collect();kv.sort_by(|a,b|b.1.cmp(&a.1).then_with(||a.0.cmp(&b.0)));st.keywords=kv.into_iter().take(6).map(|x|x.0).collect();}
#[tauri::command]fn scan_folder(root:String)->Result<ScanResult,String>{let rp=Path::new(&root);if !rp.is_dir(){return Err("선택한 경로가 폴더가 아닙니다.".into())}let mut map:HashMap<String,FolderStat>=HashMap::new();let mut excluded_paths:HashSet<String>=HashSet::new();
let walker=WalkDir::new(rp).follow_links(false).into_iter().filter_entry(|e|{if e.depth()==0{return true}let ex=e.file_type().is_dir()&&excluded(&e.file_name().to_string_lossy());if ex{excluded_paths.insert(e.path().to_string_lossy().to_string());} !ex});
for ent in walker.filter_map(Result::ok){if ent.file_type().is_dir(){continue}let md=match ent.metadata(){Ok(v)=>v,Err(_)=>continue};let parent=ent.path().parent().unwrap_or(rp);let key=parent.to_string_lossy().to_string();let name=parent.file_name().and_then(|s|s.to_str()).unwrap_or("").to_string();let st=map.entry(key.clone()).or_insert(FolderStat{path:key,name,file_count:0,total_bytes:0,extensions:HashMap::new(),recent_modified:None,representative_files:vec![],keywords:vec![]});st.file_count+=1;st.total_bytes+=md.len();if let Some(ext)=ent.path().extension().and_then(|s|s.to_str()){*st.extensions.entry(ext.to_ascii_lowercase()).or_insert(0)+=1}if st.representative_files.len()<12{st.representative_files.push(ent.file_name().to_string_lossy().to_string())}if let Ok(m)=md.modified(){if let Ok(d)=m.duration_since(UNIX_EPOCH){let t=d.as_secs();st.recent_modified=Some(st.recent_modified.unwrap_or(0).max(t))}}}
let mut folders:Vec<_>=map.into_values().collect();for f in &mut folders{finalize(f)}folders.sort_by(|a,b|b.file_count.cmp(&a.file_count));let file_count=folders.iter().map(|f|f.file_count).sum();let total_bytes=folders.iter().map(|f|f.total_bytes).sum();let folder_count=folders.len() as u64;let scanned_at=SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_secs()*1000;Ok(ScanResult{root,scanned_at,folder_count,file_count,total_bytes,excluded_count:excluded_paths.len() as u64,folders})}
#[tauri::command]fn scan_downloads(root:String)->Result<Vec<DownloadFile>,String>{let rp=Path::new(&root);if !rp.is_dir(){return Err("선택한 다운로드 경로가 폴더가 아닙니다.".into())}let mut out=vec![];let rd=std::fs::read_dir(rp).map_err(|e|e.to_string())?;for item in rd.flatten(){let p=item.path();if !p.is_file(){continue}let md=match item.metadata(){Ok(v)=>v,Err(_)=>continue};let modified=md.modified().ok().and_then(|m|m.duration_since(UNIX_EPOCH).ok()).map(|d|d.as_secs()*1000);out.push(DownloadFile{name:item.file_name().to_string_lossy().to_string(),path:p.to_string_lossy().to_string(),size:md.len(),modified});}out.sort_by(|a,b|b.modified.cmp(&a.modified));Ok(out)}
#[tauri::command]fn validate_move_plan(download_root:String,approved_root:String,items:Vec<MovePlanItem>)->Result<Vec<MoveValidation>,String>{let dr=std::fs::canonicalize(&download_root).map_err(|e|format!("Downloads 경로 확인 실패: {e}"))?;let ar=std::fs::canonicalize(&approved_root).map_err(|e|format!("Folder Map 루트 확인 실패: {e}"))?;let mut out=vec![];for item in items{let sp=Path::new(&item.source);let tp=Path::new(&item.target);let (ok,reason)=match std::fs::canonicalize(sp){Err(_)=>(false,"원본 파일을 찾을 수 없음".to_string()),Ok(src)=>{if !src.starts_with(&dr){(false,"원본이 선택한 Downloads 밖에 있음".to_string())}else if !tp.starts_with(&ar){(false,"목적지가 승인 Folder Map 밖에 있음".to_string())}else if tp.exists(){(false,"동일 목적지 파일이 이미 존재함".to_string())}else{(true,"이동 전 안전조건 통과".to_string())}}};out.push(MoveValidation{source:item.source,target:item.target,ok,reason})}Ok(out)}
fn now_ms()->u64{SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_millis() as u64}
fn has_parent_dir(p:&Path)->bool{p.components().any(|c|matches!(c,Component::ParentDir))}
fn journal_path(app:&tauri::AppHandle)->Result<std::path::PathBuf,String>{let dir=app.path().app_data_dir().map_err(|e|e.to_string())?;std::fs::create_dir_all(&dir).map_err(|e|e.to_string())?;Ok(dir.join("move-journal.jsonl"))}
fn append_journal(app:&tauri::AppHandle,e:&JournalEntry)->Result<(),String>{let p=journal_path(app)?;let mut f=OpenOptions::new().create(true).append(true).open(p).map_err(|e|e.to_string())?;serde_json::to_writer(&mut f,e).map_err(|e|e.to_string())?;writeln!(f).map_err(|e|e.to_string())}
#[tauri::command]fn execute_move_plan(app:tauri::AppHandle,download_root:String,approved_root:String,items:Vec<MovePlanItem>)->Result<MoveExecution,String>{let checks=validate_move_plan(download_root,approved_root.clone(),items.clone())?;if checks.iter().any(|x|!x.ok){return Err("안전검증 실패 항목이 있어 이동을 중단했습니다.".into())}let ar=std::fs::canonicalize(&approved_root).map_err(|e|e.to_string())?;let tx=format!("tx-{}",now_ms());let mut results=vec![];let mut moved=0;let mut failed=0;for item in items{let tp=Path::new(&item.target);if has_parent_dir(tp)||!tp.starts_with(&ar){failed+=1;results.push(MoveValidation{source:item.source,target:item.target,ok:false,reason:"목적지 경로 안전조건 실패".into()});continue}let planned=JournalEntry{transaction_id:tx.clone(),timestamp:now_ms(),source:item.source.clone(),target:item.target.clone(),status:"planned".into(),error:None};append_journal(&app,&planned)?;if let Some(parent)=tp.parent(){if let Err(e)=std::fs::create_dir_all(parent){failed+=1;let msg=e.to_string();append_journal(&app,&JournalEntry{status:"failed".into(),error:Some(msg.clone()),..planned.clone()})?;results.push(MoveValidation{source:item.source,target:item.target,ok:false,reason:msg});continue}}match std::fs::rename(&item.source,&item.target){Ok(_)=>{moved+=1;append_journal(&app,&JournalEntry{status:"moved".into(),error:None,..planned.clone()})?;results.push(MoveValidation{source:item.source,target:item.target,ok:true,reason:"이동 완료 · Undo 가능".into()})},Err(e)=>{failed+=1;let msg=e.to_string();append_journal(&app,&JournalEntry{status:"failed".into(),error:Some(msg.clone()),..planned.clone()})?;results.push(MoveValidation{source:item.source,target:item.target,ok:false,reason:msg})}}}Ok(MoveExecution{transaction_id:tx,moved,failed,results})}
#[tauri::command]fn undo_move_transaction(app:tauri::AppHandle,transaction_id:String)->Result<MoveExecution,String>{let p=journal_path(&app)?;let f=OpenOptions::new().read(true).open(&p).map_err(|e|e.to_string())?;let mut latest:HashMap<String,JournalEntry>=HashMap::new();for line in BufReader::new(f).lines().flatten(){if let Ok(e)=serde_json::from_str::<JournalEntry>(&line){if e.transaction_id==transaction_id{latest.insert(e.source.clone(),e);}}}let mut results=vec![];let mut moved=0;let mut failed=0;for e in latest.into_values().filter(|e|e.status=="moved"){let src=Path::new(&e.source);let tgt=Path::new(&e.target);if src.exists(){failed+=1;results.push(MoveValidation{source:e.target,target:e.source,ok:false,reason:"Undo 중단: 원래 위치에 동일 경로가 이미 존재함".into()});continue}if !tgt.exists(){failed+=1;results.push(MoveValidation{source:e.target,target:e.source,ok:false,reason:"Undo 중단: 이동된 파일을 목적지에서 찾을 수 없음".into()});continue}if let Some(parent)=src.parent(){std::fs::create_dir_all(parent).map_err(|x|x.to_string())?}match std::fs::rename(tgt,src){Ok(_)=>{moved+=1;append_journal(&app,&JournalEntry{status:"undone".into(),timestamp:now_ms(),error:None,..e.clone()})?;results.push(MoveValidation{source:e.target,target:e.source,ok:true,reason:"Undo 완료".into()})},Err(x)=>{failed+=1;let msg=x.to_string();append_journal(&app,&JournalEntry{status:"undo_failed".into(),timestamp:now_ms(),error:Some(msg.clone()),..e.clone()})?;results.push(MoveValidation{source:e.target,target:e.source,ok:false,reason:msg})}}}Ok(MoveExecution{transaction_id,moved,failed,results})}
#[tauri::command]fn move_history(app:tauri::AppHandle)->Result<Vec<HistoryItem>,String>{let p=journal_path(&app)?;if !p.exists(){return Ok(vec![])}let f=OpenOptions::new().read(true).open(p).map_err(|e|e.to_string())?;let mut map:HashMap<String,HistoryItem>=HashMap::new();for line in BufReader::new(f).lines().flatten(){if let Ok(e)=serde_json::from_str::<JournalEntry>(&line){let h=map.entry(e.transaction_id.clone()).or_insert(HistoryItem{transaction_id:e.transaction_id.clone(),timestamp:e.timestamp,moved:0,undone:0,failed:0,can_undo:false});h.timestamp=h.timestamp.max(e.timestamp);match e.status.as_str(){"moved"=>h.moved+=1,"undone"=>h.undone+=1,"failed"=>h.failed+=1,_=>{}}}}let f=OpenOptions::new().read(true).open(journal_path(&app)?).map_err(|e|e.to_string())?;let mut latest:HashMap<(String,String),String>=HashMap::new();for line in BufReader::new(f).lines().flatten(){if let Ok(e)=serde_json::from_str::<JournalEntry>(&line){match e.status.as_str(){"moved"|"undone"=>{latest.insert((e.transaction_id.clone(),e.source.clone()),e.status.clone());},"undo_failed"=>{},_=>{}}}}let mut undoable:HashMap<String,bool>=HashMap::new();for ((tx,_),status) in latest{if status=="moved"{undoable.insert(tx,true);}}let mut out:Vec<_>=map.into_values().map(|mut h|{h.can_undo=*undoable.get(&h.transaction_id).unwrap_or(&false);h}).collect();out.sort_by(|a,b|b.timestamp.cmp(&a.timestamp));Ok(out)}
#[tauri::command]fn move_history_detail(app:tauri::AppHandle,transaction_id:String)->Result<HistoryDetail,String>{let p=journal_path(&app)?;if !p.exists(){return Ok(HistoryDetail{transaction_id,entries:vec![]})}let f=OpenOptions::new().read(true).open(p).map_err(|e|e.to_string())?;let mut entries=vec![];for line in BufReader::new(f).lines().flatten(){if let Ok(e)=serde_json::from_str::<JournalEntry>(&line){if e.transaction_id==transaction_id{entries.push(e)}}}entries.sort_by(|a,b|a.timestamp.cmp(&b.timestamp));Ok(HistoryDetail{transaction_id,entries})}
#[cfg_attr(mobile,tauri::mobile_entry_point)]pub fn run(){tauri::Builder::default().plugin(tauri_plugin_dialog::init()).invoke_handler(tauri::generate_handler![scan_folder,scan_downloads,validate_move_plan,execute_move_plan,undo_move_transaction,move_history,move_history_detail]).run(tauri::generate_context!()).expect("error while running FileOrbit");}