import {useMemo,useState} from "react";import {invoke} from "@tauri-apps/api/core";import {open} from "@tauri-apps/plugin-dialog";import {FolderOpen,RefreshCw,ShieldCheck,HardDrive,Files,FolderTree,Search,AlertTriangle,ClipboardList} from "lucide-react";import type {ScanResult} from "./types";import {demoScan} from "./demoData";
const fmt=(n:number)=>{const u=["B","KB","MB","GB","TB"];let i=0,v=n;while(v>=1024&&i<u.length-1){v/=1024;i++}return `${v.toFixed(i?1:0)} ${u[i]}`};
const norm=(s:string)=>s.toLowerCase().replace(/\b(19|20)\d{2}([._-]?\d{1,2})?([._-]?\d{1,2})?\b/g,"").replace(/\b(v|ver|rev)[._-]?\d+\b/g,"").replace(/[\s._-]+/g,"").replace(/\d+/g,"");
export default function App(){const isWeb=typeof window!=="undefined"&&!("__TAURI_INTERNALS__" in window);const[root,setRoot]=useState(isWeb?demoScan.root:"");const[data,setData]=useState<ScanResult|null>(isWeb?demoScan:null);const[busy,setBusy]=useState(false);const[err,setErr]=useState("");const[dry,setDry]=useState(false);
async function choose(){if(isWeb){setRoot(demoScan.root);setData({...demoScan,scannedAt:Date.now()});setDry(false);return}const p=await open({directory:true,multiple:false,title:"분석할 업무 폴더 선택"});if(typeof p==="string"){setRoot(p);setData(null);setDry(false)}}
async function scan(){if(!root)return;setBusy(true);setErr("");setDry(false);try{if(isWeb){await new Promise(r=>setTimeout(r,350));setData({...demoScan,scannedAt:Date.now()})}else setData(await invoke<ScanResult>("scan_folder",{root}))}catch(e){setErr(String(e))}finally{setBusy(false)}}
const proposals=useMemo(()=>{if(!data)return[];const groups=new Map<string,typeof data.folders>();for(const f of data.folders){const k=norm(f.name);if(k.length<2)continue;const a=groups.get(k)||[];a.push(f);groups.set(k,a)}return [...groups.entries()].filter(([,a])=>a.length>1).sort((a,b)=>b[1].length-a[1].length).slice(0,30).map(([k,a])=>({key:k,folders:a,files:a.reduce((n,f)=>n+f.fileCount,0),bytes:a.reduce((n,f)=>n+f.totalBytes,0)}))},[data]);
return <div className="shell"><aside><div className="brand"><div className="orbit">◉</div><div><b>FileOrbit</b><small>Folder Doctor</small></div></div><nav><a className={!dry?"on":""}>⌂ 홈</a><a className={dry?"on":""}>▣ 폴더 분석</a><a className="disabled">⇩ 다운로드 분석 <em>V0.3</em></a><a className="disabled">↶ 이력 / Undo <em>후속</em></a><a>⚙ 설정</a></nav><div className="safety"><ShieldCheck size={18}/><div><b>Read-only V0.1</b><span>이 버전은 파일을 이동·삭제·변경하지 않습니다.</span></div></div></aside>
<main><header><div><h1>기존 업무 폴더 분석</h1><p>정리하기 전에 현재 폴더 구조부터 이해합니다.</p></div><span className="badge">{isWeb?"WEB PREVIEW · DEMO DATA":"LOCAL ONLY"}</span></header>
<section className="hero"><div><span className="eyebrow">STEP 1 · FOLDER DOCTOR</span><h2>기존 폴더를 먼저 분석해<br/>Folder Map의 기준을 만듭니다.</h2><p>node_modules, .git, cache, temp, build 출력물은 자동 제외합니다. 분석 중에는 디스크를 변경하지 않습니다.</p></div><FolderTree size={76}/></section>
{isWeb&&<div className="webNotice"><b>GitHub Web Preview</b><span>설치 없이 화면·Dry Run 로직을 점검하는 개발 모드입니다. 실제 PC 파일에는 접근하지 않습니다.</span></div>}<section className="picker"><div className="path"><FolderOpen/><div><small>분석 루트</small><b>{root||"폴더를 선택하세요"}</b></div></div><button className="secondary" onClick={choose}>폴더 선택</button><button className="primary" disabled={!root||busy} onClick={scan}>{busy?<><RefreshCw className="spin"/> 분석 중</>:<><Search/> 읽기 전용 분석</>}</button></section>
{err&&<div className="error"><AlertTriangle/> {err}</div>}
{data&&<><section className="stats"><article><FolderTree/><span>폴더</span><b>{data.folderCount.toLocaleString()}</b></article><article><Files/><span>파일</span><b>{data.fileCount.toLocaleString()}</b></article><article><HardDrive/><span>총 용량</span><b>{fmt(data.totalBytes)}</b></article><article><ShieldCheck/><span>제외 항목</span><b>{data.excludedCount.toLocaleString()}</b></article></section>
<section className="next"><div><b>분석 완료 — 다음 단계</b><span>유사한 폴더명을 묶어 통합 후보를 찾습니다. 실제 파일은 변경하지 않습니다.</span></div><button className="primary" onClick={()=>setDry(true)}><ClipboardList/> 정리안 만들기 (Dry Run)</button></section>
{dry&&<section className="panel dry"><div className="panelHead"><div><h3>정리 제안 · Dry Run</h3><p>연도·날짜·버전 표기를 제외한 폴더명이 유사한 그룹입니다. 검토용이며 이동/삭제는 0건입니다.</p></div><span>{proposals.length}개 후보 그룹</span></div>{proposals.length?<div className="table"><div className="tr proposal th"><span>통합 후보</span><span>폴더</span><span>파일</span><span>용량</span></div>{proposals.map(p=><div className="tr proposal" key={p.key}><span><b>{p.folders.map(f=>f.name).slice(0,3).join(" · ")}</b><small>{p.folders.map(f=>f.path).slice(0,3).join("  |  ")}</small></span><span>{p.folders.length}</span><span>{p.files}</span><span>{fmt(p.bytes)}</span></div>)}</div>:<div className="emptyInline">현재 규칙으로 뚜렷한 통합 후보가 없습니다. 폴더 구조는 그대로 유지하는 쪽이 안전합니다.</div>}</section>}
<section className="panel"><div className="panelHead"><div><h3>Folder Profile</h3><p>파일 수·용량·확장자·대표 파일명·키워드 기반</p></div><span>{new Date(data.scannedAt).toLocaleString("ko-KR")}</span></div><div className="table"><div className="tr th"><span>폴더</span><span>파일</span><span>용량</span><span>대표 키워드</span></div>{data.folders.slice(0,200).map(f=><div className="tr" key={f.path}><span><b>{f.name||data.root}</b><small>{f.path}</small></span><span>{f.fileCount}</span><span>{fmt(f.totalBytes)}</span><span className="chips">{f.keywords.slice(0,4).map(k=><i key={k}>{k}</i>)}</span></div>)}</div></section></>}
{!data&&<section className="empty"><div>01</div><h3>첫 분석은 안전하게 Read-only로 시작합니다.</h3><p>분석 결과를 확인한 다음에만 폴더 통합/정리 제안(Dry Run)을 활성화합니다.</p></section>}</main></div>}