import {useState} from "react";import {invoke} from "@tauri-apps/api/core";import {open} from "@tauri-apps/plugin-dialog";import {FolderOpen,RefreshCw,ShieldCheck,HardDrive,Files,FolderTree,Search,AlertTriangle} from "lucide-react";import type {ScanResult} from "./types";
const fmt=(n:number)=>{const u=["B","KB","MB","GB","TB"];let i=0,v=n;while(v>=1024&&i<u.length-1){v/=1024;i++}return `${v.toFixed(i?1:0)} ${u[i]}`};
export default function App(){const[root,setRoot]=useState("");const[data,setData]=useState<ScanResult|null>(null);const[busy,setBusy]=useState(false);const[err,setErr]=useState("");
async function choose(){const p=await open({directory:true,multiple:false,title:"분석할 업무 폴더 선택"});if(typeof p==="string")setRoot(p)}
async function scan(){if(!root)return;setBusy(true);setErr("");try{setData(await invoke<ScanResult>("scan_folder",{root}))}catch(e){setErr(String(e))}finally{setBusy(false)}}
return <div className="shell"><aside><div className="brand"><div className="orbit">◉</div><div><b>FileOrbit</b><small>Folder Doctor</small></div></div><nav><a className="on">⌂ 홈</a><a>▣ 폴더 분석</a><a className="disabled">⇩ 다운로드 분석 <em>V0.3</em></a><a className="disabled">↶ 이력 / Undo <em>후속</em></a><a>⚙ 설정</a></nav><div className="safety"><ShieldCheck size={18}/><div><b>Read-only V0.1</b><span>이 버전은 파일을 이동·삭제·변경하지 않습니다.</span></div></div></aside>
<main><header><div><h1>기존 업무 폴더 분석</h1><p>정리하기 전에 현재 폴더 구조부터 이해합니다.</p></div><span className="badge">LOCAL ONLY</span></header>
<section className="hero"><div><span className="eyebrow">STEP 1 · FOLDER DOCTOR</span><h2>기존 폴더를 먼저 분석해<br/>Folder Map의 기준을 만듭니다.</h2><p>node_modules, .git, cache, temp, build 출력물은 자동 제외합니다. 분석 중에는 디스크를 변경하지 않습니다.</p></div><FolderTree size={76}/></section>
<section className="picker"><div className="path"><FolderOpen/><div><small>분석 루트</small><b>{root||"폴더를 선택하세요"}</b></div></div><button className="secondary" onClick={choose}>폴더 선택</button><button className="primary" disabled={!root||busy} onClick={scan}>{busy?<><RefreshCw className="spin"/> 분석 중</>:<><Search/> 읽기 전용 분석</>}</button></section>
{err&&<div className="error"><AlertTriangle/> {err}</div>}
{data&&<><section className="stats"><article><FolderTree/><span>폴더</span><b>{data.folderCount.toLocaleString()}</b></article><article><Files/><span>파일</span><b>{data.fileCount.toLocaleString()}</b></article><article><HardDrive/><span>총 용량</span><b>{fmt(data.totalBytes)}</b></article><article><ShieldCheck/><span>제외 항목</span><b>{data.excludedCount.toLocaleString()}</b></article></section>
<section className="panel"><div className="panelHead"><div><h3>Folder Profile</h3><p>파일 수·용량·확장자·대표 파일명·키워드 기반</p></div><span>{new Date(data.scannedAt).toLocaleString("ko-KR")}</span></div><div className="table"><div className="tr th"><span>폴더</span><span>파일</span><span>용량</span><span>대표 키워드</span></div>{data.folders.slice(0,200).map(f=><div className="tr" key={f.path}><span><b>{f.name||data.root}</b><small>{f.path}</small></span><span>{f.fileCount}</span><span>{fmt(f.totalBytes)}</span><span className="chips">{f.keywords.slice(0,4).map(k=><i key={k}>{k}</i>)}</span></div>)}</div></section></>}
{!data&&<section className="empty"><div>01</div><h3>첫 분석은 안전하게 Read-only로 시작합니다.</h3><p>분석 결과를 확인한 다음에만 폴더 통합/정리 제안(Dry Run)을 활성화합니다.</p></section>}
</main></div>}